name: museodeljuguetebogota
favicon: null
layout_spectrum: 0.25435
typography_spectrum: 0.73404
title: La felicidad de recordar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a6dad8'
    - '#df3e34'
    - '#ebc63b'
    - '#fff9ff'
    - '#de9335'
  brandStrength: 0.6464429721236229
  lightness: 0.5127024513203651
  saturation: 0.07432706304825842
  rhythmicContrast: 0.2309289372060448
purpose: []
